version: "3"

services:
  server:
    image: gitea/gitea:1.20.5
    container_name: gitea
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - gitea
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - ./mysql:/var/lib/mysql

#  promtail:
#    image: grafana/promtail:latest
#    command: -config.file=/etc/promtail/config.yaml
#    volumes:
#      - /promtail-config:/etc/promtail
#      - /var/log:/var/log
#    networks:
#      - gitea

volumes:
  gitea:
    driver: local
#  promtail-config:
#    driver: local

networks:
  gitea:
    external: false